openapi: 3.1.0
info:
  title: Speckle MCP Plugin API
  version: "1.0"
servers:
  - url: http://localhost:8000
paths:
  /projects:
    get:
      summary: List available projects
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
          required: false
      responses:
        '200':
          description: Project list
          content:
            text/plain:
              schema:
                type: string
  /projects/{project_id}:
    get:
      summary: Get details for a project
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
          required: false
      responses:
        '200':
          description: Project details
          content:
            text/plain:
              schema:
                type: string
  /projects/search:
    get:
      summary: Search projects by name or description
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Search results
          content:
            text/plain:
              schema:
                type: string
  /projects/{project_id}/models/{model_id}/versions:
    get:
      summary: List versions for a model
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
        - name: model_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
          required: false
      responses:
        '200':
          description: Versions list
          content:
            text/plain:
              schema:
                type: string
  /projects/{project_id}/versions/{version_id}/objects:
    get:
      summary: Retrieve objects for a version
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
        - name: version_id
          in: path
          required: true
          schema:
            type: string
        - name: include_children
          in: query
          schema:
            type: boolean
          required: false
      responses:
        '200':
          description: Version objects
          content:
            application/json:
              schema:
                type: object
  /projects/{project_id}/versions/{version_id}/query:
    get:
      summary: Query properties from a version
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
        - name: version_id
          in: path
          required: true
          schema:
            type: string
        - name: property_path
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Property value
          content:
            application/json:
              schema:
                type: object
