[project]
name = "speckle-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn>=0.34.0",
    "asyncio>=3.4.3",
    "ipykernel>=6.29.5",
    "mcp>=1.3.0",
    "specklepy==3.0.0a2",
]
